apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp-d
  labels:
    app: gowebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gowebapp
  template:
    metadata:
      labels:
        app: gowebapp
    spec:
      containers:
      - name: gowebapp
        image: rextor/go-web-app:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
