apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gowebapp-i
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: "gowebapp.local"
    http:
      paths:
      - path: "/bar/(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: gowebapp-s
            port:
              number: 80
